Address issues
FREVA-CLINT/freva-deployment pull request #105
Opened 2024-03-25 12:12 UTC by antarcticrainforest

This PR address several issues.:

- #59 created a new pipy package for the jupyter kernel install (pip install kernel-install)
- #65 version checking and installing specific versions
- #60 Adding a prefix about the deployment steps (db, databrowser etc) to each ansible task
- #57 Making ansible write in ymal instead of json format to the stdout, resulting in much better readability

I'm not expecting you to review the code changes, but it would be great. But it would be very much appreciated if you could play with it, either by using the script that sets up a local VM or using frevo-deployment.cloud.dkrz.de hostname.

2024-03-28 13:40 UTC, Karinon requested changes
I just started checking it and didn't do anything exciting at this point. My plan was at first to try deploying it on my VM vaskebjorn2 in the cloud, where previously Freva was already deployed..

First attempt:

* After entering my SSH password the shell reflects my password:

```
{'^BECOME password.*:\\s*?$': '<toomuchinformation>', '^SSH password:\\s*?$': '<toomuchinformation>'}
```
I don't like that.

* I did a `make install` previously inside my conda-env, everything seemed fine.

```
TASK [Cloning the evluation_system reposiotry] *********************************
fatal: [vaskebjorn2.cloud.dkrz.de]: FAILED! => 
  msg: |-
    Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:"root"\n:rx:allow’
    Try 'chmod --help' for more information.
    }). For information on working around this, see https://docs.ansible.com/ansible-core/2.14/user_guide/become.html#risks-of-becoming-an-unprivileged-user
```

Where does this happen? It tried it a second time after entering a deliberately wrong SSH-Password and got the same result. So it's happening on my machine?

*Second attempt:* I changed my conda env into a new env where no previous version of the deployment script was ever installed. It crashed immediately when I wanted to run the deployment:

```
ImportError: Please install the `cryptography` python module. in order to generate certificates.
```

Why isn't it installied already? After adding it via pip:

```
The command was not found or was not executable: ansible-playbook.
[14:31:22] ERROR    freva-deployment - Deployment not successful: failed         
```

Why isn't this installed already as well?

More to come as I progress..

2024-03-28 14:12 UTC, Karinon commented
> Where does this happen? It tried it a second time after entering a deliberately wrong SSH-Password and got the same result. So it's happening on my machine?

Ok, forget about that. I guess it "worked" even with wrong SSH-Key because I have a valid certificate and can login without PW...

2024-03-28 14:19 UTC, Karinon commented
FML, I was on the wrong branch... (refactor instead of versions)...I will check again..

2024-03-28 14:46 UTC, antarcticrainforest commented
I am a bit lost, so only the become permission error is an issue? The others are gone?


About the become permission issue, I have never encountered this, are you deploying this thing as root and set the admin user to something other than root?

2024-03-28 14:48 UTC, antarcticrainforest commented
Can you post the parsed inventory here, that's the yaml formatted output. The is printed to stdout before ansible starts playing the playbook

2024-03-28 14:57 UTC, Karinon commented
Sorry for the confusion. For now its only the permission-thing (and the typos). Regarding the missing deps I will try it again next week.

Here is the inventory. Right now I am only trying to deploy the core without the rest:

```
core:
  hosts: vaskebjorn2.cloud.dkrz.de
  vars:
    ansible_user: k204206
    asset_dir: /home/afast/miniconda3/share/freva/deployment
    core_ansible_python_interpreter: /home/k/k204206/mambaforge/envs/myenv/bin/python
    core_arch: linux-64
    core_dump: /tmp/AnsibleRunnerfbf1uhwr/evaluation_system.conf
    core_git_url: https://github.com/FREVA-CLINT/freva.git
    core_install_dir: /opt/frevacond
    core_keyfile: /home/afast/workspace/freva-deployment/example.crt
    core_python_version: '3.11'
    core_root_dir: /opt/frevaproj
    core_version: 2309.0.2
    debug: false
    project_name: vaskebjorn2
databrowser:
  hosts: vaskebjorn2.cloud.dkrz.de
  vars:
    ansible_user: k204206
    asset_dir: /home/afast/miniconda3/share/freva/deployment
    databrowser_ansible_python_interpreter: /home/k/k204206/mambaforge/envs/myenv/bin/python
    databrowser_email: freva@dkrz.de
    databrowser_name: vaskebjorn2-databrowser
    databrowser_version: 2403.0.2
    debug: false
    project_name: vaskebjorn2
    root_passwd: ***
    solr_version: 9.5.0
db:
  hosts: vaskebjorn2.cloud.dkrz.de
  vars:
    ansible_user: k204206
    asset_dir: /home/afast/miniconda3/share/freva/deployment
    db: evaluation_system
    db_ansible_python_interpreter: /home/k/k204206/mambaforge/envs/myenv/bin/python
    db_data_path: /opt/freva
    db_email: freva@dkrz.de
    db_name: vaskebjorn2-db
    db_passwd: M|b-Vj(KHkQqAw(674a5
    db_user: evaluation_system
    debug: false
    project_name: vaskebjorn2
    root_passwd: ***
vault:
  hosts: vaskebjorn2.cloud.dkrz.de
  vars:
    ansible_user: k204206
    asset_dir: /home/afast/miniconda3/share/freva/deployment
    debug: false
    project_name: vaskebjorn2
    root_passwd: ***
    vault_ansible_python_interpreter: /home/k/k204206/mambaforge/envs/myenv/bin/python
    vault_db_host: 127.0.0.1
    vault_db_user: evaluation_system
    vault_email_password: ''
    vault_email_user: ''
    vault_keyfile: /home/afast/workspace/freva-deployment/example.crt
    vault_name: vaskebjorn2-vault
    vault_passwd: M|b-Vj(KHkQqAw(674a5
    vault_version: 2403.2.0
web:
  hosts: vaskebjorn2.cloud.dkrz.de
  vars:
    ansible_user: k204206
    asset_dir: /home/afast/miniconda3/share/freva/deployment
    core_root_dir: /opt/frevaproj
    debug: false
    project_name: vaskebjorn2
    root_passwd: ***
    web_ansible_python_interpreter: /home/k/k204206/mambaforge/envs/myenv/bin/python
    web_name: vaskebjorn2-web
    web_version: 2403.0.0
```

2024-03-28 14:58 UTC, antarcticrainforest commented
> I just started checking it and didn't do anything exciting at this point. My plan was at first to try deploying it on my VM vaskebjorn2 in the cloud, where previously Freva was already deployed..
> 
> **First attempt:**
> 
> * I did a `make install` previously inside my conda-env, everything seemed fine.
> 
> ```
> TASK [Cloning the evluation_system reposiotry] *********************************
> fatal: [vaskebjorn2.cloud.dkrz.de]: FAILED! => 
>   msg: |-
>     Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:"root"\n:rx:allow’
>     Try 'chmod --help' for more information.
>     }). For information on working around this, see https://docs.ansible.com/ansible-core/2.14/user_guide/become.html#risks-of-becoming-an-unprivileged-user
> ```
> 
> Where does this happen? It tried it a second time after entering a deliberately wrong SSH-Password and got the same result. So it's happening on my machine?
> 
> **Second attempt:** 
> 
> I changed my conda env into a new env where no previous version of the deployment script was ever installed. It crashed immediately when I wanted to run the deployment:
> 
> ```
> ImportError: Please install the `cryptography` python module. in order to generate certificates.
> ```
> 
> Why isn't it installied already? After adding it via pip:
> 
> ```
> The command was not found or was not executable: ansible-playbook.
> [14:31:22] ERROR    freva-deployment - Deployment not successful: failed         
> ```
> 
> Why isn't this installed already as well?
> 
> More to come as I progress..

I go the this is how we deal with things at DKRZ: I think there is something wrong with your VM setting.

2024-03-28 22:21 UTC, antarcticrainforest commented
I don't see anything suspicious. Can you output the debug output, that is when you use at last `-v` flag. Something like:

```
DEBUG    freva-deployment - core:                                                                                                                                 
                      hosts: localhost                                                                                                                                       
                      vars:                                                                                                                                                  
                        ansible_user: freva                                                                                                                                  
                        asset_dir: /home/wilfred/.anaconda3/envs/python3_12/share/freva/deployment                                                                           
                        core_admin_grup: ''                                                                                                                                  
                        core_admins: wilfred                                                                                                                                 
                        core_ansible_become_user: ''                                                                                                                         
                        core_ansible_python_interpreter: /usr/bin/python3                                                                                                    
                        core_ansible_user: freva                                                                                                                             
                        core_arch: linux-64                                                                                                                                  
                        core_base_dir_location: /home/freva/freva-env/work                                                                                                   
                        core_conda_exec_path: ''                                                                                                                             
                        core_config_toml_file: /tmp/AnsibleRunnero1qiwpvs/freva_web.toml                                                                                     
                        core_dump: /tmp/AnsibleRunnero1qiwpvs/evaluation_system.conf                                                                                         
                        core_git_path: /usr/bin/git                                                                                                                          
                        core_git_url: https://github.com/FREVA-CLINT/freva.git                                                                                               
                        core_hostname: localhost                                                                                                                             
                        core_install: true                                                                                                                                   
                        core_install_dir: /opt/freva/conda                                                                                                                   
                        core_keyfile: /tmp/tmp230kuypyrandom_keys/freva.crt                                                                                                  
                        core_name: freva-core                                                                                                                                
                        core_playbook: ''                                                                                                                                    
                        core_preview_path: /home/freva/freva-env/work/share/preview                                                                                          
                        core_python_version: '3.11'                                                                                                                          
                        core_root_dir: /home/freva/freva-env                                                                                                                 
                        core_scheduler_output_dir: /home/freva/freva-env/work/share/local                                                                                    
                        core_scheduler_system: local                                                                                                                         
                        core_version: 2309.0.2                                                                                                                               
                        core_wipe: false                                                                                                                                     
                        debug: false                                                                                                                                         
                        project_name: freva 
 ```
 
 
 To be honest I still think you're doing something wrong :D

2024-03-28 22:29 UTC, antarcticrainforest commented
Ok I got this error message when I set the `ansible_become_user` to `root`

```
TASK [core - Cloning the evluation_system reposiotry] **************************
fatal: [localhost]: FAILED! => 
  msg: |-
    Failed to set permissions on the temporary files Ansible needs to create when becoming an unprivileged user (rc: 1, err: chmod: invalid mode: ‘A+user:"root"\n:rx:allow’
    Try 'chmod --help' for more information.
    }). For information on working around this, see https://docs.ansible.com/ansible-core/2.16/playbook_guide/playbooks_privilege_escalation.html#risks-of-becoming-an-unprivileged-user
```

Is this is what you are doing?

2024-04-02 09:06 UTC, Karinon commented
Just for the protocol:

Yes, it was because I set `ansible_become_user` to `root`. After I changed it the deployment continued. 

However, setting it in the TUI doesn't store the information for any other tab than `core`, so I have to re-set it every single time I want to run the deployment.

2024-04-02 09:09 UTC, Karinon commented
When I tried to set up all services at once (on the same machine I got the following error message from the deployment:

```
fatal: [vaskebjorn2.cloud.dkrz.de]: FAILED! => changed=true 
  cmd: |-
    /tmp/create_systemd.py vaskebjorn2-databrowser compose --enable --project-name vaskebjorn2-databrowser -f /opt/freva/compose_services/vaskebjorn2-databrowser-compose.yml up --remove-orphans
  delta: '0:00:00.459499'
  end: '2024-04-02 09:58:12.102638'
  msg: non-zero return code
  rc: 1
  start: '2024-04-02 09:58:11.643139'
  stderr: |-
    Job for vaskebjorn2-databrowser.service failed because the control process exited with error code.
    See "systemctl status vaskebjorn2-databrowser.service" and "journalctl -xeu vaskebjorn2-databrowser.service" for details.
    Traceback (most recent call last):
      File "/tmp/create_systemd.py", line 144, in <module>
        create_unit(*parse_args())
      File "/tmp/create_systemd.py", line 140, in create_unit
        load_unit(unit, _parse_dict(SYSTEMD_TMPL), enable)
      File "/tmp/create_systemd.py", line 79, in load_unit
        subprocess.run(cmd + ["restart", unit], check=True)
      File "/usr/lib64/python3.9/subprocess.py", line 528, in run
        raise CalledProcessError(retcode, process.args,
    subprocess.CalledProcessError: Command '['systemctl', 'restart', 'vaskebjorn2-databrowser']' returned non-zero exit status 1.
  stderr_lines: <omitted>
  stdout: ''
  stdout_lines: <omitted>
```

Then I checked `systemctl status vaskebjorn2-databrowser.service`

```
Apr 02 09:58:12 vaskebjorn2.cloud.dkrz.de sh[1144816]: yaml: unmarshal errors:
Apr 02 09:58:12 vaskebjorn2.cloud.dkrz.de sh[1144816]:   line 30: mapping key "environment" already defined at line 29
Apr 02 09:58:12 vaskebjorn2.cloud.dkrz.de systemd[1]: vaskebjorn2-databrowser.service: Control process exited, code=exited, status=15/n/a
Apr 02 09:58:12 vaskebjorn2.cloud.dkrz.de systemd[1]: vaskebjorn2-databrowser.service: Failed with result 'exit-code'.
```

The `vaskebjorn2-databrowser-compose.yml` is broken

```
  vaskebjorn2-mongo:
    image: mongo:latest
    container_name: vaskebjorn2-mongo
    hostname: vaskebjorn2-mongo
    networks:
      - vaskebjorn2-databrowser
    environment:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=search_stats
    volumes:
      - /opt/freva/vaskebjorn2/databrowser/stats:/data/db:z
    ports:
      - 27017:27017
    tty: true
```

`environment` appears twice

2024-04-08 11:59 UTC, Karinon commented on assets/share/freva/deployment/playbooks/databrowser-server-compose-template.yml
l. 35 / l. 36 in this File: Environment appears twice

2024-04-08 12:03 UTC, Karinon commented
After deleting the additional `environment` in kind of works? All Containers are up and running, but the web cannot load any assets (Css, JavaScript, Images). I assume there went something from with the collectstatic stuff. I will take a second look

2024-04-08 12:30 UTC, Karinon commented
Ok, maybe I am just dumb here: The assets cannot be loaded because `collectstatic` failed due to a `Permission denied` (which did not crash the deployment). The folder where all my configs are lying around is `/opt/freva/vaskebjorn2`:

```
drwxr-xr-x. 3 root root   19 Apr  8 14:16 databrowser
drwxr-xr-x. 6  999  999 4096 Apr  8 14:13 db_service
drwxr-xr-x. 4 8983 8983   33 Apr  8 14:16 solr_service
drwxr-xr-x. 4 root root   33 Apr  8 14:11 vault_service
drwxr-xr-x. 4 root root  126 Apr  8 14:18 web_service
```

The files inside `web_service` (e.g. `static`) belong to `root`. Did I fuck it up? I was pretty sure that I removed root everywhere as the `become`-user. Anyway, this is the reason why collectstatic fails.

2024-04-08 19:28 UTC, MoSHad91 commented
To systematically monitor potential errors, I attempted a deployment and encountered the same issue previously reported by @Karinon at #55. Attached is my .toml file for reference. And also the solution is, downloading the `evaluation_system.conf` from freva repo and put it in the mentioned directory in the error.

```bash
           INFO     freva-deployment - Creating evaluation_system.conf                                                                                                                    
Traceback (most recent call last):
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/deploy-freva", line 8, in <module>
    sys.exit(tui())
             ^^^^^
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/ui/deployment_tui/__init__.py", line 64, in tui
    DF.play(ask_pass, verbosity, ssh_port=ssh_port)
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/error.py", line 52, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 735, in play
    return self._play(
           ^^^^^^^^^^^
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 857, in _play
    self.create_eval_config()
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 665, in create_eval_config
    with cfg_file.open() as f_obj:
         ^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment/config/evaluation_system.conf.tmpl'
```

[conf.toml.txt](https://github.com/FREVA-CLINT/freva-deployment/files/14909357/conf.toml.txt)

2024-04-08 19:32 UTC, MoSHad91 commented
I've also encountered an issue with deleting the vault_name container. Does anyone have any suggestions on how to overcome this challenge?


```bash
freva-deployment on  versions [!?] via 🐍 v3.12.2 via 🅒 freva-dev took 1m30s 
✦2 ❯ deploy-freva
Playing steps: core, databrowser, db, web with ansible
Give the password elevating user privilege (sudo): 
Getting versions of micro-services ... ok
[21:19:33] INFO     freva-deployment - Creating Ansible playbooks                                                                                                                         
Choose a master password, this password will be used to:
- create the mysql root password
- set the django admin web password
- set the mongo db user password
Note: Ideally this password can be shared amongst other admins.
choose master password: 
re-enter master password: 

The web will need login credentials to connect to the mail server that has been set up.
You should now enter your login credentials.
Note:These credentials will be securely stored in an encrypted vault

Username for mail server: 
Password for mail server: 
[21:19:46] INFO     freva-deployment - Parsing configurations                                                                                                                             
core:
  hosts: 192.168.0.25
  vars:
    ansible_user: k202187
    asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
    core_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
    core_arch: osx-64
    core_dump: /var/folders/99/_rg5v0pn0sq81l0rr5g0z20h0000gn/T/AnsibleRunnerfd93y6qf/evaluation_system.conf
    core_git_url: https://github.com/FREVA-CLINT/freva.git
    core_install_dir: /opt/anaconda3/envs/freva-dev
    core_keyfile: /Users/mo/Downloads/freva.crt
    core_python_version: '3.11'
    core_root_dir: /opt/anaconda3/envs/freva-dev/env/freva-env
    core_version: 2309.0.2
    debug: true
    project_name: regiklim
databrowser:
  hosts: 192.168.0.25
  vars:
    ansible_user: mo
    asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
    databrowser_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
    databrowser_email: data@dkrz.de
    databrowser_name: regiklim-databrowser
    databrowser_version: 2403.0.2
    debug: true
    project_name: regiklim
    root_passwd: ***
    solr_version: 9.5.0
db:
  hosts: 192.168.0.25
  vars:
    ansible_user: k202187
    asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
    db: evaluation_system
    db_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
    db_data_path: /opt/freva
    db_email: data@dkrz.de
    db_name: regiklim-db
    db_passwd: 7_F*iWZ@q1NyLN22%yVJ
    db_user: evaluation_system
    debug: true
    project_name: regiklim
    root_passwd: ***
vault:
  hosts: 192.168.0.25
  vars:
    ansible_user: k202187
    asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
    debug: true
    project_name: regiklim
    root_passwd: ***
    vault_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
    vault_db_host: 127.0.0.1
    vault_db_user: evaluation_system
    vault_email_password: ''
    vault_email_user: ''
    vault_keyfile: /Users/mo/Downloads/freva.crt
    vault_name: regiklim-vault
    vault_passwd: 7_F*iWZ@q1NyLN22%yVJ
    vault_version: 2403.2.0
web:
  hosts: 192.168.0.25
  vars:
    ansible_user: k202187
    asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
    core_root_dir: /opt/anaconda3/envs/freva-dev/env/freva-env
    debug: true
    project_name: regiklim
    root_passwd: ***
    web_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
    web_name: regiklim-web
    web_version: 2403.0.0

           INFO     freva-deployment - Creating evaluation_system.conf                                                                                                                    
           INFO     freva-deployment - Playing the playbooks for core, vault, db, databrowser, web with ansible                                                                           
BECOME password: 

PLAY [core] ********************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.0.25]

TASK [core - Cleaning up temporary files] **************************************
ok: [192.168.0.25]

TASK [core - Cloning the evluation_system reposiotry] **************************
changed: [192.168.0.25]

TASK [core - Getting status of the conda env] **********************************
ok: [192.168.0.25]

TASK [core - Installing temp micromamba] ***************************************
skipping: [192.168.0.25]

TASK [core - Installing freva] *************************************************
skipping: [192.168.0.25]

TASK [core - Check if mamba exists] ********************************************
ok: [192.168.0.25]

TASK [core - Set variable for package manager] *********************************
ok: [192.168.0.25]

TASK [core - Updating existing freva] ******************************************
changed: [192.168.0.25]

TASK [core - Preparing creation of directory structure] ************************
ok: [192.168.0.25]

TASK [core - Creating directory structure] *************************************
ok: [192.168.0.25] => (item=/opt/anaconda3/envs/freva-dev/env/freva-env/freva/)
ok: [192.168.0.25] => (item=/opt/anaconda3/envs/freva-dev/env/freva-env/plugins/)

TASK [core - Creating user work directory] *************************************
ok: [192.168.0.25]

TASK [core - Creating workload manager output] *********************************
ok: [192.168.0.25]

TASK [core - Creating preview path] ********************************************
ok: [192.168.0.25]

TASK [core - Registering evaluation_sytem path] ********************************
ok: [192.168.0.25]

TASK [core - Inserting evaluation_sytem.conf file] *****************************
skipping: [192.168.0.25]

TASK [core - Inserting evaluation_system.config file to temp location] *********
changed: [192.168.0.25]

TASK [core - Inserting evaluation_system.conf file] ****************************
skipping: [192.168.0.25]

TASK [core - Installing additional python packages] ****************************
changed: [192.168.0.25] => (item=kernel-install)
changed: [192.168.0.25] => (item=metadata-inspector)

TASK [core - Getting status of drs_config.toml file] ***************************
ok: [192.168.0.25]

TASK [core - Inserting drs_config.toml file] ***********************************
skipping: [192.168.0.25]

TASK [core - Configuring evaluation_system] ************************************
changed: [192.168.0.25]

TASK [core - Copying Public key file] ******************************************
changed: [192.168.0.25]

TASK [core - Deleting temporary files] *****************************************
changed: [192.168.0.25]

PLAY [vault] *******************************************************************

TASK [Gathering Facts] *********************************************************
ok: [192.168.0.25]

TASK [vault - Copying docker/podman wrapper script] ****************************
ok: [192.168.0.25]

TASK [vault - Registering systemctl path] **************************************
ok: [192.168.0.25]

TASK [vault - Registering vault volume path] ***********************************
ok: [192.168.0.25]

TASK [vault - Set vault valume path] *******************************************
ok: [192.168.0.25]

TASK [vault - Stopping services and deleting existing containers] **************
changed: [192.168.0.25]

TASK [vault - Pulling container] ***********************************************
changed: [192.168.0.25]

TASK [vault - Copying systemd files] *******************************************
ok: [192.168.0.25]

TASK [vault - [...]

2024-04-09 07:05 UTC, antarcticrainforest commented
> To systematically monitor potential errors, I attempted a deployment and encountered the same issue previously reported by @Karinon at #55. Attached is my .toml file for reference. And also the solution is, downloading the `evaluation_system.conf` from freva repo and put it in the mentioned directory in the error.
> 
> ```shell
>            INFO     freva-deployment - Creating evaluation_system.conf                                                                                                                    
> Traceback (most recent call last):
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/deploy-freva", line 8, in <module>
>     sys.exit(tui())
>              ^^^^^
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/ui/deployment_tui/__init__.py", line 64, in tui
>     DF.play(ask_pass, verbosity, ssh_port=ssh_port)
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/error.py", line 52, in wrapper
>     return func(*args, **kwargs)
>            ^^^^^^^^^^^^^^^^^^^^^
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 735, in play
>     return self._play(
>            ^^^^^^^^^^^
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 857, in _play
>     self.create_eval_config()
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/site-packages/freva_deployment/deploy.py", line 665, in create_eval_config
>     with cfg_file.open() as f_obj:
>          ^^^^^^^^^^^^^^^
>   File "/opt/anaconda3/envs/freva-dev/envs/freva-dev/lib/python3.12/pathlib.py", line 1013, in open
>     return io.open(self, mode, buffering, encoding, errors, newline)
>            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
> FileNotFoundError: [Errno 2] No such file or directory: '/opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment/config/evaluation_system.conf.tmpl'
> ```
> 
> [conf.toml.txt](https://github.com/FREVA-CLINT/freva-deployment/files/14909357/conf.toml.txt)

Sorry, since the modern build systems do not offer something like a pre or post-build phase we had to outsource downloading the the file via make:

```console
make develop
``` 

This is to download the file and install all dependencies. 

The release is created by a CI that downloads the file to make sure it is aboard when the package gets created.

2024-04-09 07:09 UTC, antarcticrainforest commented
> I've also encountered an issue with deleting the vault_name container. Does anyone have any suggestions on how to overcome this challenge?
> 
> ```shell
> freva-deployment on  versions [!?] via 🐍 v3.12.2 via 🅒 freva-dev took 1m30s 
> ✦2 ❯ deploy-freva
> Playing steps: core, databrowser, db, web with ansible
> Give the password elevating user privilege (sudo): 
> Getting versions of micro-services ... ok
> [21:19:33] INFO     freva-deployment - Creating Ansible playbooks                                                                                                                         
> Choose a master password, this password will be used to:
> - create the mysql root password
> - set the django admin web password
> - set the mongo db user password
> Note: Ideally this password can be shared amongst other admins.
> choose master password: 
> re-enter master password: 
> 
> The web will need login credentials to connect to the mail server that has been set up.
> You should now enter your login credentials.
> Note:These credentials will be securely stored in an encrypted vault
> 
> Username for mail server: 
> Password for mail server: 
> [21:19:46] INFO     freva-deployment - Parsing configurations                                                                                                                             
> core:
>   hosts: 192.168.0.25
>   vars:
>     ansible_user: k202187
>     asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
>     core_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
>     core_arch: osx-64
>     core_dump: /var/folders/99/_rg5v0pn0sq81l0rr5g0z20h0000gn/T/AnsibleRunnerfd93y6qf/evaluation_system.conf
>     core_git_url: https://github.com/FREVA-CLINT/freva.git
>     core_install_dir: /opt/anaconda3/envs/freva-dev
>     core_keyfile: /Users/mo/Downloads/freva.crt
>     core_python_version: '3.11'
>     core_root_dir: /opt/anaconda3/envs/freva-dev/env/freva-env
>     core_version: 2309.0.2
>     debug: true
>     project_name: regiklim
> databrowser:
>   hosts: 192.168.0.25
>   vars:
>     ansible_user: mo
>     asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
>     databrowser_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
>     databrowser_email: data@dkrz.de
>     databrowser_name: regiklim-databrowser
>     databrowser_version: 2403.0.2
>     debug: true
>     project_name: regiklim
>     root_passwd: ***
>     solr_version: 9.5.0
> db:
>   hosts: 192.168.0.25
>   vars:
>     ansible_user: k202187
>     asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
>     db: evaluation_system
>     db_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
>     db_data_path: /opt/freva
>     db_email: data@dkrz.de
>     db_name: regiklim-db
>     db_passwd: 7_F*iWZ@q1NyLN22%yVJ
>     db_user: evaluation_system
>     debug: true
>     project_name: regiklim
>     root_passwd: ***
> vault:
>   hosts: 192.168.0.25
>   vars:
>     ansible_user: k202187
>     asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
>     debug: true
>     project_name: regiklim
>     root_passwd: ***
>     vault_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
>     vault_db_host: 127.0.0.1
>     vault_db_user: evaluation_system
>     vault_email_password: ''
>     vault_email_user: ''
>     vault_keyfile: /Users/mo/Downloads/freva.crt
>     vault_name: regiklim-vault
>     vault_passwd: 7_F*iWZ@q1NyLN22%yVJ
>     vault_version: 2403.2.0
> web:
>   hosts: 192.168.0.25
>   vars:
>     ansible_user: k202187
>     asset_dir: /opt/anaconda3/envs/freva-dev/envs/freva-dev/share/freva/deployment
>     core_root_dir: /opt/anaconda3/envs/freva-dev/env/freva-env
>     debug: true
>     project_name: regiklim
>     root_passwd: ***
>     web_ansible_python_interpreter: /opt/anaconda3/envs/freva-dev/envs/freva-dev/bin/python
>     web_name: regiklim-web
>     web_version: 2403.0.0
> 
>            INFO     freva-deployment - Creating evaluation_system.conf                                                                                                                    
>            INFO     freva-deployment - Playing the playbooks for core, vault, db, databrowser, web with ansible                                                                           
> BECOME password: 
> 
> PLAY [core] ********************************************************************
> 
> TASK [Gathering Facts] *********************************************************
> ok: [192.168.0.25]
> 
> TASK [core - Cleaning up temporary files] **************************************
> ok: [192.168.0.25]
> 
> TASK [core - Cloning the evluation_system reposiotry] **************************
> changed: [192.168.0.25]
> 
> TASK [core - Getting status of the conda env] **********************************
> ok: [192.168.0.25]
> 
> TASK [core - Installing temp micromamba] ***************************************
> skipping: [192.168.0.25]
> 
> TASK [core - Installing freva] *************************************************
> skipping: [192.168.0.25]
> 
> TASK [core - Check if mamba exists] ********************************************
> ok: [192.168.0.25]
> 
> TASK [core - Set variable for package manager] *********************************
> ok: [192.168.0.25]
> 
> TASK [core - Updating existing freva] ******************************************
> changed: [192.168.0.25]
> 
> TASK [core - Preparing creation of directory structure] ************************
> ok: [192.168.0.25]
> 
> TASK [core - Creating directory structure] *************************************
> ok: [192.168.0.25] => (item=/opt/anaconda3/envs/freva-dev/env/freva-env/freva/)
> ok: [192.168.0.25] => (item=/opt/anaconda3/envs/freva-dev/env/freva-env/plugins/)
> 
> TASK [core - Creating user work directory] *************************************
> ok: [192.168.0.25]
> 
> TASK [core - Creating workload manager output] *********************************
> ok: [192.168.0.25]
> 
> TASK [core - Creating preview path] ********************************************
> ok: [192.168.0.25]
> 
> TASK [core - Registering evaluation_sytem path] ********************************
> ok: [192.168.0.25]
> 
> TASK [core - Inserting evaluation_sytem.conf file] *****************************
> skipping: [192.168.0.25]
> 
> TASK [core - Inserting evaluation_system.config file to temp location] *********
> changed: [192.168.0.25]
> 
> TASK [core - Inserting evaluation_system.conf file] ****************************
> skipping: [192.168.0.25]
> 
> TASK [core - Installing additional python packages] ****************************
> changed: [192.168.0.25] => (item=kernel-install)
> changed: [192.168.0.25] => (item=metadata-inspector)
> 
> TASK [core - Getting status of drs_config.toml file] ***************************
> ok: [192.168.0.25]
> 
> TASK [core - Inserting drs_config.toml file] ***********************************
> skipping: [192.168.0.25]
> 
> TASK [core - Configuring evaluation_system] ************************************
> changed: [192.168.0.25]
> 
> TASK [core - Copying Public key file] ******************************************
> changed: [192.168.0.25]
> 
> TASK [core - Deleting temporary files] *****************************************
> changed: [192.168.0.25]
> 
> PLAY [vault] *******************************************************************
> 
> TASK [Gathering Facts] *********************************************************
> ok: [192.168.0.25]
> 
> TASK [vault - Copying docker/podman wrapper script] ****************************
> ok: [192.168.0.25]
> 
> TASK [vault - Registering systemctl path] **************************************
> ok: [192.168.0.25]
> 
> TASK [vault - Registering vault volume path] ***********************************
> ok: [192.168.0.25]
> 
> TASK [vault - Set vault valume path] **** [...]

2024-04-09 08:16 UTC, MoSHad91 commented
Thanks @antarcticrainforest for reply, 

Alright, it seems there are two approaches to take care of this issue. First, developing `create_systemd.py` which `systemd` command needs to be replaced with `launchd` when we choose `set the target architecture of the system` as `osx64` or `osx-arm64`. Second as you mentioned changing the playbooks instructions to start without `systemd` unit.
Should I open the issue or you already opened an issue for this?

2024-04-09 08:34 UTC, antarcticrainforest commented
> Thanks @antarcticrainforest for reply,
> 
> Alright, it seems there are two approaches to take care of this issue. First, developing `create_systemd.py` which `systemd` command needs to be replaced with `launchd` when we choose `set the target architecture of the system` as `osx64` or `osx-arm64`. Second as you mentioned changing the playbooks instructions to start without `systemd` unit. Should I open the issue or you already opened an issue for this?

To me it seems best to let the create_systemd.py script choose what it should do in order to start and register the service. Of course the name of the script shouldn't be create_systemd anymore, something like create_service.py. If you want you can give it a crack.

2024-04-09 09:59 UTC, MoSHad91 commented
New error:
I cloned the `versions` branch of repo and ran with the same configuration again, but I got a databrowserAPI unreachable issue:

```bash
❯ deploy-freva-cmd --config ../inventory.toml
Give the password elevating user privilege (sudo): 
Getting versions of micro-services ... fail
BECOME password: 

PLAY [databrowser] *************************************************************

TASK [Gathering Facts] *********************************************************
fatal: [levantedatabrowser]: UNREACHABLE! => changed=false 
  msg: 'Failed to connect to the host via ssh: ssh: Could not resolve hostname levantedatabrowser: nodename nor servname provided, or not known'
  unreachable: true

PLAY RECAP *********************************************************************
levantedatabrowser         : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   

[11:48:28] ERROR    freva-deployment - DeploymentError: Deployment failed!
``` 

I checked recent iterations of databrowserAPI in `versions.json` and it's still `"databrowser": "2403.0.2",`.
Here is my [freva_deployment.json](https://github.com/FREVA-CLINT/freva-deployment/files/14917006/freva_deployment.json).

Can you please give me your `freva_deployment.json` file which is located in your cache directory to make a comparison and find the issue?
And have you ever faced this issue?

2024-04-09 11:53 UTC, antarcticrainforest commented
> @antarcticrainforest I cloned the `versions` branch of repo and ran with the same configuration again, but I got a databrowserAPI unreachable issue:
> 
> ```shell
> ❯ deploy-freva-cmd --config ../inventory.toml
> Give the password elevating user privilege (sudo): 
> Getting versions of micro-services ... fail
> BECOME password: 
> 
> PLAY [databrowser] *************************************************************
> 
> TASK [Gathering Facts] *********************************************************
> fatal: [levantedatabrowser]: UNREACHABLE! => changed=false 
>   msg: 'Failed to connect to the host via ssh: ssh: Could not resolve hostname levantedatabrowser: nodename nor servname provided, or not known'
>   unreachable: true
> 
> PLAY RECAP *********************************************************************
> levantedatabrowser         : ok=0    changed=0    unreachable=1    failed=0    skipped=0    rescued=0    ignored=0   
> 
> [11:48:28] ERROR    freva-deployment - DeploymentError: Deployment failed!
> ```
> 
> I checked recent iterations of databrowserAPI in `versions.json` and it's still `"databrowser": "2403.0.2",`. Here is my [freva_deployment.json](https://github.com/FREVA-CLINT/freva-deployment/files/14917006/freva_deployment.json).
> 
> Can you please give me your `freva_deployment.json` file which is located in your cache directory to make a comparison and find the issue? And have you ever faced this issue?

Thats because levantedatabrowser doesn't exist. Are you sure  these hostnames levantedb, levantedatabrowser etc actually exist?

2024-04-09 11:57 UTC, antarcticrainforest commented
> Ok, maybe I am just dumb here: The assets cannot be loaded because `collectstatic` failed due to a `Permission denied` (which did not crash the deployment). The folder where all my configs are lying around is `/opt/freva/vaskebjorn2`:
> 
> ```
> drwxr-xr-x. 3 root root   19 Apr  8 14:16 databrowser
> drwxr-xr-x. 6  999  999 4096 Apr  8 14:13 db_service
> drwxr-xr-x. 4 8983 8983   33 Apr  8 14:16 solr_service
> drwxr-xr-x. 4 root root   33 Apr  8 14:11 vault_service
> drwxr-xr-x. 4 root root  126 Apr  8 14:18 web_service
> ```
> 
> The files inside `web_service` (e.g. `static`) belong to `root`. Did I fuck it up? I was pretty sure that I removed root everywhere as the `become`-user. Anyway, this is the reason why collectstatic fails.

@Karinon could it be that there is some SELinux magic going on? The user inside the container is freva now. Remember we die this because we had some issues. I am getting more and more confused with SELinux and containers, a it doesn't seem to be fully encapsulated. I'll your settings next thing

2024-04-09 12:46 UTC, MoSHad91 commented
I did deploy the versions branch of freva-deployment and from my end it's done and ready to merge 

[freva_dep.log](https://github.com/FREVA-CLINT/freva-deployment/files/14918688/freva_dep.log)
[freva_deployment.json](https://github.com/FREVA-CLINT/freva-deployment/files/14918689/freva_deployment.json)
[inventory.toml](https://github.com/FREVA-CLINT/freva-deployment/files/14918695/inventory.toml.txt)

2024-04-09 13:01 UTC, antarcticrainforest commented
Great thanks @MoSHad91 ,

that was fast. I took a look at your inventory.toml file and I am surprised that this worked. The arch settings in the core deployment for the mamba env still point to osx-arm, which makes me wonder if there is something wrong, because it worked.

Could you also double-check if the web site is up and running?

2024-04-09 14:54 UTC, MoSHad91 commented
> Great thanks @MoSHad91 ,
> 
> that was fast. I took a look at your inventory.toml file and I am surprised that this worked. The arch settings in the core deployment for the mamba env still point to osx-arm, which makes me wonder if there is something wrong, because it worked.
> 
> Could you also double-check if the web site is up and running?

@antarcticrainforest, I think choosing arch doesn't make any effect on the process of deployment. But I gotta have a look at the source code. My host for all is `freva-plugin-playground` vm and deployment got finished without stop or error. i have to mention I got some skipped(!). I ran it again with verbose option and arc as linux-64 and my log is here:
[freva_dep_new.log](https://github.com/FREVA-CLINT/freva-deployment/files/14920227/freva_dep_new.log)
Also this is the `docker ps` result, but I cannot see any web service and port here:

```bash
d695e31cb096   redis                                      "docker-entrypoint.s…"   56 seconds ago   Up 55 seconds   0.0.0.0:6379->6379/tcp, :::6379->6379/tcp             regiklim-redis
615621ef2ae7   mongo:latest                               "docker-entrypoint.s…"   4 minutes ago    Up 4 minutes    0.0.0.0:27017->27017/tcp, :::27017->27017/tcp         regiklim-mongo
189f4659a92f   ghcr.io/freva-clint/freva-vault:2403.2.0   "docker-entrypoint.s…"   9 minutes ago    Up 9 minutes    0.0.0.0:5002->5002/tcp, :::5002->5002/tcp, 8200/tcp   regiklim-vault
b135e012dbb9   solr:latest                                "docker-entrypoint.s…"   2 weeks ago      Up 2 weeks      0.0.0.0:8983->8983/tcp, :::8983->8983/tcp             freva_solr_1
975f4452e7f4   mariadb:latest                             "docker-entrypoint.s…"   2 weeks ago      Up 2 weeks      0.0.0.0:3306->3306/tcp, :::3306->3306/tcp             freva_db_1
```

But as you see I have no Django with 8000 port, in docker running service in the list.

2024-04-18 19:21 UTC, antarcticrainforest commented
@MoSHad91 @Karinon  I am going ahead and merge this. There is still plenty of opportunity to play with this in the refactor branch.

2024-04-18 19:21 UTC, merged