New vault
FREVA-CLINT/freva-deployment pull request #54
Opened 2023-12-07 06:56 UTC by antarcticrainforest

We have witnessed problems with the vault server in the past. This aims at fixing this.

What this does fixing possible race conditions where the a process tried to unseal the vault before the vault server was up. I've also changed the restAPI to fastAPI.

Additionally, the httpd/web app trying to connect to the reverse proxy/redis service via alias names assigned by docker-compose. This seems to be a better option.

2024-01-18 14:30 UTC, Karinon requested changes

2024-01-18 14:30 UTC, Karinon commented on src/freva_deployment/deploy.py
> +        _webserver_items["REDIS_HOST"] = "{self.project_name}-web"
Several issues here:

1. forgot the formatting `f` at the beginning
2. I assume you wanted to set it to f"{self.project_name}-redis", as it is running not in the same container, as the web
3. See the other comment regarding the change in HTTPD

2024-01-18 14:30 UTC, Karinon commented on assets/share/freva/deployment/playbooks/web-server-playbook.yml
> +        -e FREVA_HOST="{{project_name}}-web" -p 80:80 -p 443:443
I had to revert this change on my test-VM in order to make this run as I was not able to establish a connection from the HTTP-Container to the Web-Container tested via curl

I am not sure what caused my issue. Either I have missed some general settings for my podman or we need to take care of our network-options in the corresponding docker-compose file

2024-01-18 15:29 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +    url: str
The first parameter is called `enpoint` in the signature and `url` in the docstring

2024-01-18 15:59 UTC, Karinon requested changes

2024-01-18 15:59 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +            if response.status_code >= 200 and response.status_code < 300:
If the error case happens (status_code > 300), I would really like to see what happened in the logs of the corresponding docker container. The way how this is implemented prevents this.

2024-01-18 15:59 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +        except json.JSONDecodeError:
Why exactly don't you want to show this error message?

2024-01-18 15:59 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +    for _ in range(10):
What would happen on an exception which is not handled here? (i.e. the generic RequestException). Do we dont expect them to happen?

2024-01-18 15:59 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +def login(token: str) -> None:
This is more of a generic comment/question and not necessarily an issue. I noticed some patterns in this file which I would love to understand better:

1. Many of the functions (e.g. login) just terminate or return an empty dict in case of errors. Where do we deal with those errors? Do we even need to deal with them and if not, why not?
2. Who calls login? Is there some FastAPI-Magic which I don't see?

2024-01-23 22:27 UTC, antarcticrainforest commented on src/freva_deployment/deploy.py
> +        _webserver_items["REDIS_HOST"] = "{self.project_name}-web"
1 - 2: correct.

2024-01-23 22:37 UTC, antarcticrainforest commented on assets/share/freva/deployment/playbooks/web-server-playbook.yml
> +        -e FREVA_HOST="{{project_name}}-web" -p 80:80 -p 443:443
True, these changes will anyway be overridden, with the new docker-compose style.

2024-01-23 22:39 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +    url: str
true

2024-01-23 22:45 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +            if response.status_code >= 200 and response.status_code < 300:
It actually shows up, if a status_code was received the loop breaks (line 104) and an error message is emitted (line 110)

2024-01-23 22:48 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +        except json.JSONDecodeError:
the decoder error message? I figured that it would show up in the `response.text` which is then added to the log. But I can also define a custom log message, like unable to decode json object or something.

2024-01-23 22:51 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +    for _ in range(10):
I'll use a generic catch then.

2024-01-23 23:10 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +def login(token: str) -> None:
Errors are logged in the `interact_with_vault` method, if something goes wrong. Empty dicts are returned for because the return values of successful commands are json objects, and if something goes wrong an error is logged at least the correct data structure is returned (although empty). But then at least foo.get("bar") would work in both cases.

For the login question. The login function is called by the unseal method and this method shows the design.

we try to unseal the vault with the unseal key (put). If that fails `interact_with_vault` will log an error and return an empty dict. Then we only have to check if the sealed flag is set and false in the returned dict to do the login. If not the vault remains sealed and the command was not successful. So the idea is that there is always an error log if something goes wrong and an empty dict.

2024-01-23 23:29 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +def login(token: str) -> None:
I didn't answer the login question properly. The unsealing and login happens when the runserver.py is run as a script. FastAPI hasn't anything to do with this. You only have to make sure to run this file as a script before starting uvicorn and fastAPI. Hence

```
CMD /bin/runserver.py && uvicorn --workers 2 --app-dir /bin runserver:app --host 0.0.0.0 --port 5002
```
in the Dockerfile. 

It's not pretty and I am sure I could have fastAPI instructed to unseal the vault on startup, but there must have been a reason why I chose that way, I can't tell you why though.

2024-01-25 07:37 UTC, antarcticrainforest commented
@Karinon

2024-02-02 15:50 UTC, antarcticrainforest commented on assets/share/freva/deployment/playbooks/web-server-playbook.yml
> +        -e FREVA_HOST="{{web_server_name}}" -p 80:80 -p 443:443
The docker-compose style hasn't made it's way into main. 

There is a branch that still needs merging. I will update this branch once this PR here has been merged.

2024-02-08 07:55 UTC, antarcticrainforest commented on assets/share/freva/deployment/playbooks/web-server-playbook.yml
> +        -e FREVA_HOST="{{project_name}}-web" -p 80:80 -p 443:443
I think that should be solved now? Or is it not?

2024-02-08 07:56 UTC, antarcticrainforest commented on assets/share/freva/deployment/vault/runserver.py
> +def login(token: str) -> None:
Is that still an issue?

2024-02-08 10:20 UTC, Karinon approved these changes
LGTM

2024-02-08 10:20 UTC, Karinon commented on assets/share/freva/deployment/playbooks/web-server-playbook.yml
> +        -e FREVA_HOST="{{project_name}}-web" -p 80:80 -p 443:443
Yeah, it is. I just don't get why this has to be now in the old-syntax again, but you have the "new" syntax in deploy.py in line 235 for redis.

But it works, so you can resolve this..

2024-02-08 10:20 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +    for _ in range(10):
resolved

2024-02-08 10:20 UTC, Karinon commented on assets/share/freva/deployment/vault/runserver.py
> +def login(token: str) -> None:
There was no issue, just understanding problems from my side. Is resolved.

2024-02-14 13:34 UTC, merged